### ISSUE TITLE
hap-eval crashes on attached VCF

### ISSUE THREAD

**Issue by archmageirvine** [Sentieon/hap-eval#3]
On the attached VCF:
```
hap_eval -r ~/ref/38/Homo_sapiens_assembly38.fasta -b subset.vcf.gz -c subset.vcf.gz -i example.bed
```
produces:
```
Traceback (most recent call last):
  File "/home/sean/hap-eval/venv/lib/python3.7/site-packages/vcflib/sharder.py", line 54, in apply
    rv = func(*av, **kw)
  File "/home/sean/hap-eval/venv/lib/python3.7/site-packages/hap_eval/hap_eval.py", line 345, in evaluate
    for g in self.cluster(vcfs, contig, start, end, maxdist, pred):
  File "/home/sean/hap-eval/venv/lib/python3.7/site-packages/hap_eval/hap_eval.py", line 190, in cluster
    v = next(i, None)
  File "/home/sean/hap-eval/venv/lib/python3.7/site-packages/vcflib/vcf.py", line 411, in __next__
    return self.first()
  File "/home/sean/hap-eval/venv/lib/python3.7/site-packages/vcflib/vcf.py", line 390, in first
    v = self.vcf.next()
  File "/home/sean/hap-eval/venv/lib/python3.7/site-packages/vcflib/vcf.py", line 307, in __next__
    v = self.parse(line)
  File "/home/sean/hap-eval/venv/lib/python3.7/site-packages/vcflib/vcf.py", line 193, in parse
    info = dict(map(self.parse_info, vals[7].split(';')))
  File "/home/sean/hap-eval/venv/lib/python3.7/site-packages/vcflib/vcf.py", line 183, in parse_info
    return self.parse_field(self.infos, self.parse_kv(kv))
  File "/home/sean/hap-eval/venv/lib/python3.7/site-packages/vcflib/vcf.py", line 177, in parse_field
    v = list(map(cvt, v.split(',')))
AttributeError: 'bool' object has no attribute 'split'
...
```
where the contents of example.bed are:
```
chr1    65418   65433
```
[subset.vcf.gz](https://github.com/Sentieon/hap-eval/files/10006726/subset.vcf.gz)

**Comment by DonFreed** [comment]
Thank you for the detailed error message and the example VCF file. The `REF_TRF` flag is causing problems with hap-eval's VCF parsing, which is causing the error message you are seeing.

Can you try pre-processing your VCF with the [cleanup script](https://github.com/Sentieon/hap-eval/blob/main/scripts/cleanup_vcf.py)? This would be the usage for the subset.vcf.gz file:
```
python ./scripts/cleanup_vcf.py --input subset.vcf.gz --output subset_cleaned.vcf.gz
```
The script will remove the `REF_TRF` flags from the VCF, allowing the parser to read the file.

**Comment by archmageirvine** [comment]
Yes, that worked, thanks. Also on the full sample.

**Comment by archmageirvine** [comment]
I think it would be nice if whatever cleaning in done by `./scripts/cleanup_vcf.py` could be rolled into `hap-eval` itself to avoid the need for generating yet another set of intermiediate files.

**Comment by DonFreed** [comment]
Glad this worked!

The cleanup script removes extra INFO/FORMAT tags that are not used by `hap-eval`. The drawback of applying this cleanup approach universally is that the annotated VCFs that are output by `hap-eval` would lose some annotations from the input VCFs.

We can consider adding something like a `--cleanup` argument to `hap-eval`, that would perform the same handling with a temp file.

**Comment by DonFreed** [comment]
The library used for VCF parsing parses the full VCF record, regardless if all the data is needed by `hap-eval`. We'll look into options for improving our handling input VCFs.
